### ISSUE TITLE
Student name tough to read on screen

### ISSUE THREAD

**Issue by ErnieAtLYD** [Aereli/WynRandoGenerator#9]
### Reproduction
1. Go to https://priceless-shannon-9f6e3f.netlify.com/
2. Click on "Generate Random Student"
3. The student name appears.
### Expected
The student name should be easily readable, especially on a projector.
### Actual
The student name is black on dark blue which is tough to read on a laptop, tougher to see if this was on a projector.

### Screenshot
![image](https://user-images.githubusercontent.com/33945/78899796-e749ea80-7a43-11ea-9c7f-1ec178e18fa7.png)

**Comment by Aereli** [comment]
color has been changed
